# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Demo-Blog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo-Blog
  pod 'BluePine', '0.1.7'
  pod 'IQKeyboardManagerSwift'

end
